kind: pipeline
name: build

platform:
  os: linux

steps:
- name: build
  image: plugins/docker
  settings:
    repo: ghcr.io/kubernetize/unbound
    registry: ghcr.io
    auto_tag: true
    username: rkojedzinszky
    password:
      from_secret: ghcr.io.password
    mirror:
      from_secret: hub_docker_mirror
