kind: pipeline
name: build

platform:
  os: linux

steps:
- name: build
  image: plugins/docker
  settings:
    repo: kubernetize/unbound
    auto_tag: true
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password
