kind: pipeline
name: manifest

platform:
  os: linux

steps:
- image: plugins/manifest
  settings:
    auto_tag: true
    username: rkojedzinszky
    password:
      from_secret: hub_docker_password

depends_on: []
