apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
spec:
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
      - image: ghcr.io/kubernetize/unbound
        name: unbound
      securityContext:
        runAsNonRoot: true
        sysctls:
        - name: net.ipv4.ip_unprivileged_port_start
          value: "0"
